"""
app.py - The Pipeline Infrastructure
DO NOT EDIT THIS FILE unless you are modifying the core GCS handling logic.
Biologists: Please place your code in `model.py`.
"""

import os
import signal
import shutil
from flask import Flask, request, Response, jsonify
from flask_cors import CORS
from waitress import serve
from google.cloud import storage

# Import the user's custom model logic
import model
from utils.payload_utils import parse_execution_payload
from utils.utils import ( write_json_output_to_gcs)


app = Flask(__name__)
CORS(app)

def handle_sigterm(*args):
    """
    Handle forceful container termination gracefully.
    
    Parameters
    ----------
    *args : tuple
        Variable length argument list passed by the signal handler.
    """
    print("Received SIGTERM, shutting down gracefully...")
    for item in os.listdir("/tmp"):
        if item.startswith("run_"):
            shutil.rmtree(os.path.join("/tmp", item), ignore_errors=True)
    os._exit(0)

def download_gcs_uri(client: storage.Client, uri: str, destination: str):
    """
    Downloads a single GCS file to a local destination.
    
    Parameters
    ----------
    client : storage.Client
        The instantiated Google Cloud Storage client.
    uri : str
        The full gs:// URI of the file to download.
    destination : str
        The local file path where the file should be saved.
    """
    bucket_name = uri.replace("gs://", "").split("/")[0]
    blob_path = "/".join(uri.replace("gs://", "").split("/")[1:])
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    blob.download_to_filename(destination)

def upload_gcs_uri(client: storage.Client, local_path: str, uri: str, content_type="application/json"):
    """
    Uploads a local file to a GCS destination.
    
    Parameters
    ----------
    client : storage.Client
        The instantiated Google Cloud Storage client.
    local_path : str
        The local file path of the file to upload.
    uri : str
        The full gs:// URI destination.
    content_type : str, optional
        The MIME type of the file being uploaded (default is "application/json").
    """
    bucket_name = uri.replace("gs://", "").split("/")[0]
    blob_path = "/".join(uri.replace("gs://", "").split("/")[1:])
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(blob_path)
    blob.upload_from_filename(local_path, content_type=content_type)

@app.route("/isalive")
def is_alive():
    """Vertex AI liveness/readiness probe."""
    return Response(status=200)

@app.route("/predict", methods=["POST"])
def predict():
    payload_data = request.get_json()
    
    try:
        jobs = parse_execution_payload(
            payload_data, 
            schema_path="json_schema/predict_endpoint_schema.json"
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 400

    results = []
    for job in jobs:
        res = model.run_model(
            input_files=job["input_files"],
            output_path=job.get("output_path"),
            config=job.get("config", {})
        )
        
        # Upload individual instance result JSON to GCS if specified
        json_out = job.get("json_output_location")
        if json_out:
            write_json_output_to_gcs(res, json_out)

        results.append(res)

    return jsonify({"predictions": results, "status": "success"})
if __name__ == "__main__":    
    # 360000 seconds = 100 hours. This is the maximum length timeout.
    # Prevents Waitress from closing socket on massive, multi-hour video inference pipelines.
    CHANNEL_TIMEOUT = 360000  
    print("Waitress WSGI Server is starting up...")
    print("Listening on: http://0.0.0.0:8080")
    print(f"Channel timeout set to {CHANNEL_TIMEOUT}s")

    signal.signal(signal.SIGTERM, handle_sigterm)
    serve(app, host="0.0.0.0", port=8080, channel_timeout=CHANNEL_TIMEOUT)
